-file("/usr/local/lib/erlang/lib/parsetools-2.0.5/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(luerl_scan).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/luerl_scan.xrl", 115).

-export([is_keyword/1]).

%% name_token(Chars, Line) ->
%%     {token,{'NAME',Line,Symbol}} | {Name,Line} | {error,E}.
%% Build a name from list of legal characters, else error.

name_token(Cs, L) ->
    case catch {ok,list_to_atom(Cs)} of
	{ok,Name} ->
	    case is_keyword(Name) of
		true -> {token,{Name,L}};
		false -> {token,{'NAME',L,Name}}
	    end;
	_ -> {error,"illegal name"}
    end.

%% base_token(Chars, Base, Line) -> Integer.
%% Convert a string of Base characters into a number. We know that
%% the strings only contain the correct character.

base_token(Cs, B, L) ->
    case base1(Cs, B, 0) of
	{N,[]} -> {token,{'INTEGER',L,N}};
	{_,_} -> {error,"illegal based number"}
    end.

base1([C|Cs], Base, SoFar) when C >= $0, C =< $9, C < Base + $0 ->
    Next = SoFar * Base + (C - $0),
    base1(Cs, Base, Next);
base1([C|Cs], Base, SoFar) when C >= $a, C =< $f, C < Base + $a - 10 ->
    Next = SoFar * Base + (C - $a + 10),
    base1(Cs, Base, Next);
base1([C|Cs], Base, SoFar) when C >= $A, C =< $F, C < Base + $A - 10 ->
    Next = SoFar * Base + (C - $A + 10),
    base1(Cs, Base, Next);
base1([C|Cs], _Base, SoFar) -> {SoFar,[C|Cs]};
base1([], _Base, N) -> {N,[]}.

%% chars(InputChars) -> Chars.
%% Convert an input string into the corresponding string
%% characters. We know that the input string is correct.

chars([$\\,$x,C|Cs0]) ->
    case hex_char(C) of
	true ->
	    case base1([C|Cs0], 16, 0) of
		{N,[$;|Cs1]} -> [N|chars(Cs1)];
		_Other -> [escape_char($x)|chars([C|Cs0])]
	    end;
	false -> [escape_char($x)|chars([C|Cs0])]
    end;
chars([$\\,C|Cs]) -> [escape_char(C)|chars(Cs)];
chars([C|Cs]) -> [C|chars(Cs)];
chars([]) -> [].

hex_char(C) when C >= $0, C =< $9 -> true;
hex_char(C) when C >= $a, C =< $f -> true;
hex_char(C) when C >= $A, C =< $F -> true;
hex_char(_) -> false.

escape_char($n) -> $\n;				%\n = LF
escape_char($r) -> $\r;				%\r = CR
escape_char($t) -> $\t;				%\t = TAB
escape_char($v) -> $\v;				%\v = VT
escape_char($b) -> $\b;				%\b = BS
escape_char($f) -> $\f;				%\f = FF
escape_char($e) -> $\e;				%\e = ESC
escape_char($s) -> $\s;				%\s = SPC
escape_char($d) -> $\d;				%\d = DEL
escape_char(C) -> C.

long_bracket(Line, [$\n|Cs]) ->
    S = list_to_binary(chars(Cs)),
     {token,{'STRING',Line,S}};
long_bracket(Line, Cs) ->
    S = list_to_binary(chars(Cs)),
     {token,{'STRING',Line,S}}.

%% is_keyword(Name) -> boolean().
%% Test if the name is a keyword.

is_keyword('and') -> true;
is_keyword('break') -> true;
is_keyword('do') -> true;
is_keyword('else') -> true;
is_keyword('elseif') -> true;
is_keyword('end') -> true;
is_keyword('false') -> true;
is_keyword('for') -> true;
is_keyword('function') -> true;
is_keyword('goto') -> true;
is_keyword('if') -> true;
is_keyword('in') -> true;
is_keyword('local') -> true;
is_keyword('nil') -> true;
is_keyword('not') -> true;
is_keyword('or') -> true;
is_keyword('repeat') -> true;
is_keyword('return') -> true;
is_keyword('then') -> true;
is_keyword('true') -> true;
is_keyword('until') -> true;
is_keyword('while') -> true;
is_keyword(_) -> false.

-file("/usr/local/lib/erlang/lib/parsetools-2.0.5/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/luerl_scan.erl", 381).
yystate() -> 60.

yystate(63, [120|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [101|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [69|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [46|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(39, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,63};
yystate(62, [10|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line+1, Tlen+1, 35, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(62, Ics, Line, Tlen+1, 35, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(62, Ics, Line, Tlen+1, 35, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,62};
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,61};
yystate(60, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line+1, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 32 ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(59, Ics, Line, Tlen+1, 3, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,59};
yystate(58, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line+1, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(57, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,57};
yystate(56, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(51, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(51, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(51, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,51};
yystate(50, [92|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 5, Tlen);
yystate(50, [34|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 5, Tlen);
yystate(50, [10|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line+1, Tlen+1, 5, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(58, Ics, Line, Tlen+1, 5, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(58, Ics, Line, Tlen+1, 5, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(58, Ics, Line, Tlen+1, 5, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(58, Ics, Line, Tlen+1, 5, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,50};
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(49, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,49};
yystate(48, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(47, [101|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [69|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(47, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,47};
yystate(46, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(46, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(46, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line+1, Tlen+1, Action, Alen);
yystate(46, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(46, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(46, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(46, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(46, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,46};
yystate(45, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(44, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(43, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,43};
yystate(42, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(41, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 0, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 0, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 0, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 0, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,40};
yystate(39, [46|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(39, Ics, Line, Tlen+1, 1, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,39};
yystate(38, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(37, [46|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 32, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line,37};
yystate(36, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 4, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,35};
yystate(34, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line+1, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, [46|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 33, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,33};
yystate(32, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(29, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line};
yystate(28, [91|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 26, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,28};
yystate(27, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [92|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, [39|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, [10|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line+1, Tlen+1, 6, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(34, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(34, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(34, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(34, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,26};
yystate(25, [45|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,25};
yystate(24, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line+1, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 92 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 94 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,24};
yystate(23, [101|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 1, Tlen);
yystate(23, [69|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 1, Tlen);
yystate(23, [46|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(39, Ics, Line, Tlen+1, 1, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,23};
yystate(22, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line+1, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line+1, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 90 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 92 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line+1, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 92 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 94 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,20};
yystate(19, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(18, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(17, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,17};
yystate(16, [93|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,16};
yystate(15, [58|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 30, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,15};
yystate(14, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(13, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line+1, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 92 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 94 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, [61|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 20, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,12};
yystate(11, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(10, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(9, [93|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 37, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line,9};
yystate(8, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(7, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(6, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(5, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line+1, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 92 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 94 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, [61|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 21, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line,4};
yystate(3, [61|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 19, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,3};
yystate(2, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(1, Ics, Line, Tlen+1, 36, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(1, Ics, Line, Tlen+1, 36, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,1};
yystate(0, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLen, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLen, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLen, TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, _, _, TokenLine) ->
    yyaction_27(TokenLine);
yyaction(28, _, _, TokenLine) ->
    yyaction_28(TokenLine);
yyaction(29, _, _, TokenLine) ->
    yyaction_29(TokenLine);
yyaction(30, _, _, TokenLine) ->
    yyaction_30(TokenLine);
yyaction(31, _, _, TokenLine) ->
    yyaction_31(TokenLine);
yyaction(32, _, _, TokenLine) ->
    yyaction_32(TokenLine);
yyaction(33, _, _, TokenLine) ->
    yyaction_33(TokenLine);
yyaction(34, _, _, TokenLine) ->
    yyaction_34(TokenLine);
yyaction(35, _, _, _) ->
    yyaction_35();
yyaction(36, _, _, _) ->
    yyaction_36();
yyaction(37, _, _, _) ->
    yyaction_37();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("src/luerl_scan.xrl", 39).
yyaction_0(TokenChars, TokenLine) ->
     name_token (TokenChars, TokenLine) .

-compile({inline,yyaction_1/2}).
-file("src/luerl_scan.xrl", 42).
yyaction_1(TokenChars, TokenLine) ->
     case catch { ok, list_to_integer (TokenChars) } of
     { ok, I } -> { token, { 'NUMBER', TokenLine, float (I) } } ;
     _ -> { error, "illegal number" }
     end .

-compile({inline,yyaction_2/2}).
-file("src/luerl_scan.xrl", 47).
yyaction_2(TokenChars, TokenLine) ->
     base_token (string : substr (TokenChars, 3), 16, TokenLine) .

-compile({inline,yyaction_3/2}).
-file("src/luerl_scan.xrl", 50).
yyaction_3(TokenChars, TokenLine) ->
     case catch { ok, list_to_float (TokenChars) } of
     { ok, F } -> { token, { 'NUMBER', TokenLine, F } } ;
     _ -> { error, "illegal number" }
     end .

-compile({inline,yyaction_4/2}).
-file("src/luerl_scan.xrl", 55).
yyaction_4(TokenChars, TokenLine) ->
     [M, E ] = string : tokens (TokenChars, "eE"),
     case catch { ok, list_to_float (M ++ ".0e" ++ E) } of
     { ok, F } -> { token, { 'NUMBER', TokenLine, F } } ;
     _ -> { error, "illegal number" }
     end .

-compile({inline,yyaction_5/3}).
-file("src/luerl_scan.xrl", 64).
yyaction_5(TokenChars, TokenLen, TokenLine) ->
     Cs = string : substr (TokenChars, 2, TokenLen - 2),
     S = list_to_binary (chars (Cs)),
     { token, { 'STRING', TokenLine, S } } .

-compile({inline,yyaction_6/3}).
-file("src/luerl_scan.xrl", 69).
yyaction_6(TokenChars, TokenLen, TokenLine) ->
     Cs = string : substr (TokenChars, 2, TokenLen - 2),
     S = list_to_binary (chars (Cs)),
     { token, { 'STRING', TokenLine, S } } .

-compile({inline,yyaction_7/3}).
-file("src/luerl_scan.xrl", 74).
yyaction_7(TokenChars, TokenLen, TokenLine) ->
     Cs = string : substr (TokenChars, 3, TokenLen - 4),
     long_bracket (TokenLine, Cs) .

-compile({inline,yyaction_8/1}).
-file("src/luerl_scan.xrl", 78).
yyaction_8(TokenLine) ->
     { token, { '+', TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("src/luerl_scan.xrl", 79).
yyaction_9(TokenLine) ->
     { token, { '-', TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("src/luerl_scan.xrl", 80).
yyaction_10(TokenLine) ->
     { token, { '*', TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("src/luerl_scan.xrl", 81).
yyaction_11(TokenLine) ->
     { token, { '/', TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("src/luerl_scan.xrl", 82).
yyaction_12(TokenLine) ->
     { token, { '%', TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("src/luerl_scan.xrl", 83).
yyaction_13(TokenLine) ->
     { token, { '^', TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("src/luerl_scan.xrl", 84).
yyaction_14(TokenLine) ->
     { token, { '#', TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("src/luerl_scan.xrl", 85).
yyaction_15(TokenLine) ->
     { token, { '==', TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("src/luerl_scan.xrl", 86).
yyaction_16(TokenLine) ->
     { token, { '~=', TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("src/luerl_scan.xrl", 87).
yyaction_17(TokenLine) ->
     { token, { '<=', TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("src/luerl_scan.xrl", 88).
yyaction_18(TokenLine) ->
     { token, { '>=', TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("src/luerl_scan.xrl", 89).
yyaction_19(TokenLine) ->
     { token, { '<', TokenLine } } .

-compile({inline,yyaction_20/1}).
-file("src/luerl_scan.xrl", 90).
yyaction_20(TokenLine) ->
     { token, { '>', TokenLine } } .

-compile({inline,yyaction_21/1}).
-file("src/luerl_scan.xrl", 91).
yyaction_21(TokenLine) ->
     { token, { '=', TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("src/luerl_scan.xrl", 92).
yyaction_22(TokenLine) ->
     { token, { '(', TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("src/luerl_scan.xrl", 93).
yyaction_23(TokenLine) ->
     { token, { ')', TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("src/luerl_scan.xrl", 94).
yyaction_24(TokenLine) ->
     { token, { '{', TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("src/luerl_scan.xrl", 95).
yyaction_25(TokenLine) ->
     { token, { '}', TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("src/luerl_scan.xrl", 96).
yyaction_26(TokenLine) ->
     { token, { '[', TokenLine } } .

-compile({inline,yyaction_27/1}).
-file("src/luerl_scan.xrl", 97).
yyaction_27(TokenLine) ->
     { token, { ']', TokenLine } } .

-compile({inline,yyaction_28/1}).
-file("src/luerl_scan.xrl", 98).
yyaction_28(TokenLine) ->
     { token, { '::', TokenLine } } .

-compile({inline,yyaction_29/1}).
-file("src/luerl_scan.xrl", 99).
yyaction_29(TokenLine) ->
     { token, { ';', TokenLine } } .

-compile({inline,yyaction_30/1}).
-file("src/luerl_scan.xrl", 100).
yyaction_30(TokenLine) ->
     { token, { ':', TokenLine } } .

-compile({inline,yyaction_31/1}).
-file("src/luerl_scan.xrl", 101).
yyaction_31(TokenLine) ->
     { token, { ',', TokenLine } } .

-compile({inline,yyaction_32/1}).
-file("src/luerl_scan.xrl", 102).
yyaction_32(TokenLine) ->
     { token, { '.', TokenLine } } .

-compile({inline,yyaction_33/1}).
-file("src/luerl_scan.xrl", 103).
yyaction_33(TokenLine) ->
     { token, { '..', TokenLine } } .

-compile({inline,yyaction_34/1}).
-file("src/luerl_scan.xrl", 104).
yyaction_34(TokenLine) ->
     { token, { '...', TokenLine } } .

-compile({inline,yyaction_35/0}).
-file("src/luerl_scan.xrl", 106).
yyaction_35() ->
     skip_token .

-compile({inline,yyaction_36/0}).
-file("src/luerl_scan.xrl", 109).
yyaction_36() ->
     skip_token .

-compile({inline,yyaction_37/0}).
-file("src/luerl_scan.xrl", 111).
yyaction_37() ->
     skip_token .

-file("/usr/local/lib/erlang/lib/parsetools-2.0.5/include/leexinc.hrl", 282).
